# cloudbuild.yaml  (commit this to the repo root)
substitutions:
  _REGION: europe-west1
  _SERVICE: delivery-api
  _REPO: delivery-backend            # Artifact Registry repo
  _PROJECT_ID: $PROJECT_ID           # Cloud Build injects this
  _IMAGE: ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/app:$SHORT_SHA

steps:
  # 1) Build the container from backend/Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', '${_IMAGE}', '.']

  # 2) Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  # 3) Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE}'
      - '--image=${_IMAGE}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--timeout=300'
      - '--set-env-vars=SPREADSHEET_ID=$$SPREADSHEET_ID,DELIVERY_GUY_NAME=$$DELIVERY_GUY_NAME,WEB_CONCURRENCY=1'
      - '--update-secrets=GOOGLE_CREDENTIALS_B64=GOOGLE_CREDENTIALS_B64:latest'
    secretEnv: ['SPREADSHEET_ID','DELIVERY_GUY_NAME']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/SPREADSHEET_ID/versions/latest
      env: 'SPREADSHEET_ID'
    - versionName: projects/$PROJECT_ID/secrets/DELIVERY_GUY_NAME/versions/latest
      env: 'DELIVERY_GUY_NAME'
