###############################################################
# Render “Blueprint” – pasting this into Render creates &
# links both services (backend + Expo Web PWA) automatically.
###############################################################
services:
  # ───────────────────────────────────────── backend
  - type: web
    name: delivery-backend
    env: docker
    rootDir: backend
    plan: free
    region: frankfurt        # or your nearest region
    healthCheckPath: /health
    autoDeploy: true
    dockerCommand: ""        # Render uses the CMD in Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false          # add value in dashboard
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  # ───────────────────────────────────────── Expo web build
  - type: static
    name: delivery-web
    rootDir: app             # Expo project lives here
    buildCommand: |
      npx expo export:web --non-interactive --output-dir dist
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
