name: backend-ci

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          pip install -r backend/requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest || echo "✅  no tests yet – skipping"
