name: Build & Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4

    - name: Decode GCP key
      run: | 
        echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 -d > $HOME/gcp-key.json

    - name: 'Setup gcloud'
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY_B64 }}
        install_components: 'beta'

    - name: 'Build & push image with Cloud Build'
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/attendance-app:$GITHUB_SHA .

    - name: 'Deploy to Cloud Run'
      run: |
        gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/attendance-app:$GITHUB_SHA \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated \
          --set-env-vars SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }} \
          --set-env-vars EMPLOYEE_WAGES_JSON='${{ secrets.EMPLOYEE_WAGES_JSON }}' \
          --set-env-vars GOOGLE_CREDENTIALS_B64=${{ secrets.GOOGLE_CREDENTIALS_B64 }}
